# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

platform :ios do
  desc "Push a new beta build to TestFlight"
  lane :beta do
    # increment_build_number(xcodeproj: "iDogYears2.xcodeproj")
    setup_ci if ENV['CI']
    create_keychain(
      name: ENV["CI_KEYCHAIN_NAME"],
      password: ENV["CI_KEYCHAIN_PASSWORD"],
      default_keychain: true,
      unlock: true,
      timeout: 3600,
      lock_when_sleeps: false
    )
    match(
      type: "appstore", 
      keychain_name: ENV["CI_KEYCHAIN_NAME"],
      keychain_password: ENV["CI_KEYCHAIN_PASSWORD"],
      readonly: true,
      shallow_clone: true,
      verbose: false,
      clone_branch_directly: true,
    )
    build_app(scheme: "iDogYears2")
    # upload_to_testflight
  end
end

# ,
# export_options: {
#  method: "app-store",
#  provisioningProfiles: {
#    "com.fekke.dogyearspaid" => "e812d9b8-0d00-466a-81e9-f1302243a1c3"
#  },
#  signingCertificate: "Apple Distribution: David Fekke (JXRDDKQ33V)"
#}
