# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

before_all do
  ENV['FASTLANE_USER'] = 'david@fekke.com' # Replace with your GitHub username
  ENV['FASTLANE_PASSWORD'] = ENV['GH_ACCESS_TOKEN']
  # ... other configurations
end


platform :ios do
  desc "Push a new release build to the App Store"
  lane :release do
    increment_build_number(xcodeproj: "iDogYears2.xcodeproj")
    build_app(scheme: "iDogYears2")
    upload_to_app_store
  end

  desc "Run a build of the project"
  lane :build do
    setup_ci
    match(
      type: "appstore",
      git_url: "https://davidfekke:${GH_ACCESS_TOKEN}@github.com/davidfekke/match.git", 
      readonly: true
    )

    get_provisioning_profile
    build_app(scheme: "iDogYears2",
      export_options: {
        provisioningProfiles: {
          "com.fekke.dogyearspaid" => "AppStore_com.fekke.dogyearspaid"
        }
      }
    )
  end

  desc "Sync development"
  lane :sync do
    lane :beta do
      get_certificates           # invokes cert
      get_provisioning_profile   # invokes sigh
    end
  end
end

