
name: Xcode Build and Archive

on:
  push:
    branches: [ master ]

jobs:
  build:

    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v3
    - name: Xcode version
      run: /usr/bin/xcodebuild -version
    - name: Build iDogYears iOS app
      run: fastlane ios build
