
name: Xcode Build and Archive

on:
  push:
    branches: [ master ]

jobs:
  build:

    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v3
    - name: Xcode version
      run: /usr/bin/xcodebuild -version
    - name: Clone repository
      run: git clone https://<TOKEN>@github.com/davidfekke/match.git
      env:
        TOKEN: ${{ secrets.GH_TOKEN }}
    - name: Build iDogYears iOS app
      run: fastlane ios beta
      env:
        GH_TOKEN: ${{ secrets.GH_TOKEN }}
        MATCH_PASSWORD: ${{ secrets.MATCH_PASSWORD }}
