
name: Xcode Build and Archive

on:
  push:
    branches: [ master ]

jobs:
  build:

    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v2
    - name: Xcode version
      run: /usr/bin/xcodebuild -version
	- name: Decrypt and install certs and profiles
      run: ./.github/secrets/decrypt_secret.sh
      env:
        PASSPHRASE: ${{ secrets.PASSPHRASE }}
	- name: Build iDogYears iOS app
	  run: xcodebuild -sdk iphoneos -project iDogYears2.xcodeproj -configuration Automatic -scheme iDogYears2
